function DrawSkeleton(POINTS) %#ok<INUSD>
 txt = csvimport('export-AD_dreapta_sus.csv'); close all;
 fields = {'head_x','head_y', 'head_z', 'neck_x','neck_y','neck_z',... 
    'left_shoulder_x', 'left_shoulder_y','left_shoulder_z',...
    'right_shoulder_x','right_shoulder_y','right_shoulder_z',...
 	  'left_elbow_x','left_elbow_y','left_elbow_z', ... 
      'right_elbow_x','right_elbow_y','right_elbow_z',... 
      'left_hand_x','left_hand_y','left_hand_z', ...
      'right_hand_x','right_hand_y', 'right_hand_z' ...
 	  'torso_x','torso_y','torso_z', 'left_hip_x','left_hip_y','left_hip_z',... 
      'right_hip_x','right_hip_y','right_hip_z','left_knee_x','left_knee_y','left_knee_z',...
      'right_knee_x','right_knee_y','right_knee_z',...
           'left_foot_x','left_foot_y','left_foot_z',...
           'right_foot_x','right_foot_y','right_foot_z'};
 POINTS1 =cell2struct(txt, fields, 2);   
 POINTS=POINTS1(2:end,1); clear POINTS1; % 1st Row = Headers
 no_skeletal = size(POINTS,1); % acum din read_skel:
  grid on;
 
 i = 1;
while i <= no_skeletal
    PTS = POINTS(i,1);
    x = [PTS.head_x PTS.left_elbow_x PTS.left_foot_x PTS.left_hand_x PTS.left_hip_x PTS.left_knee_x ... 
    PTS.left_shoulder_x  PTS.neck_x PTS.right_elbow_x PTS.right_foot_x PTS.right_hand_x PTS.right_hip_x ...
    PTS.right_knee_x PTS.right_shoulder_x PTS.torso_x ];
    %xmin = min(x);x1=x-xmin; clear xmin; % create array of positive abscisas
     xlim([min(x(:)) max(x(:))]);
    
     plot([min(x(:)),  max(x(:))], [0, 0]); hold on;
     
    y = [PTS.head_y PTS.left_elbow_y PTS.left_foot_y PTS.left_hand_y PTS.left_hip_y PTS.left_knee_y ... 
    PTS.left_shoulder_y PTS.neck_y PTS.right_elbow_y PTS.right_foot_y PTS.right_hand_y PTS.right_hip_y ...
    PTS.right_knee_y PTS.right_shoulder_y PTS.torso_y ];
    %ymin = min(y);y1=y-ymin; clear ymin; % create array of positive abscisas
     ylim([min(y(:)) max(y(:))]);

      plot([0, 0], [min(y(:)), max(y(:))]);    hold on;
     
    z = [PTS.head_z PTS.left_elbow_z PTS.left_foot_z PTS.left_hand_z PTS.left_hip_z PTS.left_knee_z ... 
    PTS.left_shoulder_z PTS.neck_z PTS.right_elbow_z PTS.right_foot_z PTS.right_hand_z PTS.right_hip_z ...
    PTS.right_knee_z PTS.right_shoulder_z PTS.torso_z ];
    %ymin = min(y);y1=y-ymin; clear ymin; % create array of positive abscisas
      zlim([min(z(:)) max(z(:))]);

        plot([0, 0], [min(z(:)), max(z(:))]);    hold on;
     title(['Image is for frame Number: ', num2str(i)])
    xlabel('x')
    ylabel('y')
    zlabel('depth')
    grid on
      
    %1: Head-Neck
    plot3([PTS.head_x, PTS.neck_x]',[ PTS.head_y,  PTS.neck_y]', [PTS.head_z, PTS.neck_z]',...
        '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y'); 
        axis equal;
        hold on;
    
    %2:  LftShou-Neck
    plot3([PTS.left_shoulder_x, PTS.neck_x],[PTS.left_shoulder_y, PTS.neck_y],[PTS.left_shoulder_z, PTS.neck_z],...
        '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y'); 
        hold on;
    
    %3:  RightShoulder-Neck
    plot3([PTS.right_shoulder_x, PTS.neck_x],[PTS.right_shoulder_y, PTS.neck_y],[PTS.right_shoulder_z, PTS.neck_z],...
        '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y'); 
    hold on;
    
    %4:  Left_Shoulder - Torso-Center 
    plot3([PTS.left_shoulder_x, PTS.torso_x],[PTS.left_shoulder_y, PTS.torso_y],[PTS.left_shoulder_z, PTS.torso_z],...
        '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y');
    hold on;
    
    %5:  Right_Shoulder - Torso-Center 
    plot3([PTS.right_shoulder_x, PTS.torso_x],[PTS.right_shoulder_y, PTS.torso_y],[PTS.right_shoulder_z, PTS.torso_z],...
          '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y'); 
    hold on;
    
    %6: Torso_Center - Left_Hip
    plot3([PTS.torso_x, PTS.left_hip_x],[PTS.torso_y, PTS.left_hip_y],[PTS.torso_z, PTS.left_hip_z],...
          '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y'); 
    hold on;
    
    %7: Torso_Center - Right_Hip
    plot3([PTS.torso_x, PTS.right_hip_x],[PTS.torso_y, PTS.right_hip_y],[PTS.torso_z, PTS.right_hip_z],...
          '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y'); 
    hold on;
    
    %8: Left_Shoulder - Left_Elbow
    plot3([PTS.left_shoulder_x, PTS.left_elbow_x],[PTS.left_shoulder_y, PTS.left_elbow_y],[PTS.left_shoulder_z, PTS.left_elbow_z],...
          '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y'); 
    hold on;
    
    %9:  Left_Elbow - Left_Hand
    plot3([PTS.left_elbow_x, PTS.left_hand_x],[PTS.left_elbow_y, PTS.left_hand_y],[PTS.left_elbow_z, PTS.left_hand_z],...
           '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y');
    hold on;
    
    %10: Right_Shoulder - Right_Elbow
    plot3([PTS.right_shoulder_x, PTS.right_elbow_x],[PTS.right_shoulder_y, PTS.right_elbow_y],[PTS.right_shoulder_z, PTS.right_elbow_z],...
          '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y'); 
    hold on;
      
    %11:   Right_Elbow - Right_Hand
    plot3([PTS.right_elbow_x, PTS.right_hand_x],[PTS.right_elbow_y, PTS.right_hand_y],[PTS.right_elbow_z, PTS.right_hand_z],...
           '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y');
    hold on;
    
    
    %12: Left_Hip - Left_Knee  
    plot3([PTS.left_hip_x, PTS.left_knee_x ],[PTS.left_hip_y, PTS.left_knee_y ],[PTS.left_hip_z, PTS.left_knee_z],...
           '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y');
    hold on;
    
    %13: Left_Knee  - Left_foot
    plot3([PTS.left_knee_x, PTS.left_foot_x],[PTS.left_knee_y, PTS.left_foot_y],[PTS.left_knee_z, PTS.left_foot_z],...
           '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y');
    hold on;
    
    %14: Right_Hip - Right_Knee  
    plot3([PTS.right_hip_x, PTS.right_knee_x ],[PTS.right_hip_y, PTS.right_knee_y],[PTS.right_hip_z, PTS.right_knee_z],...
           '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y');
    hold on;
       
    %15: Right_Knee  - Right_foot
    plot3([PTS.right_knee_x, PTS.right_foot_x],[PTS.right_knee_y, PTS.right_foot_y],[PTS.right_knee_z, PTS.right_foot_z],...
           '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y');
    hold on; 
    
    %16: Left_Hip  - Right_Hip
    plot3([PTS.left_hip_x, PTS.right_hip_x],[PTS.left_hip_y, PTS.right_hip_y],[PTS.left_hip_z, PTS.right_hip_z],...
           '-bo', 'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerEdgeColor','k', ...
        'MarkerFaceColor','y');
    hold on; 
    
    
    drawnow; disp('Press a key to advance to next figure')
    pause;
     clf reset; close all; %clear figure's props
    
    i = i+ 1; % jump to next recorded skeleton
   
end
