from os import listdir
from pprint import pprint
import requests

from sky_biometrics.face_client import FaceClient

API_KEY = '711d297cb9a04301a97ef06d33916fae'
API_SECRET = '3c989bc2209e47f2aecba4ef116cec58'

NAMESPACE = 'amilab-test2'
LABELS = {'andrei': 'Andrei Ismail',
          'diana': 'Diana Tatu'}

PREFIX_URL = "https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/{person_name}@amilab.ro/"
TRAIN_FOLDER = "/home/diana/ami/AmI-Platform/face_samples/train/{person_name}/"
TEST_FOLDER = "/home/diana/ami/AmI-Platform/face_samples/test/{person_name}/"

client = FaceClient(API_KEY, API_SECRET)

# Training step
tids = {}
for person_name in ['andrei', 'diana']:
    # Train namespace with person's face samples
    face_samples = []

    for image in listdir(TRAIN_FOLDER.format(person_name=person_name)):
        image_url = "%s%s" % (PREFIX_URL.format(person_name=person_name), image)
        response = requests.get(image_url)
        if response.status_code == 200:
            face_samples.append(image_url)
    face_samples = ','.join(face_samples)

    print("Detecting faces for %s..." % person_name)
    response = client.faces_detect(face_samples, aggressive=True)
    pprint(response)

    print("Saving tags for %s..." % person_name)
    tids[person_name] = [photo['tags'][0]['tid'] for photo in response['photos']]
    client.tags_save(tids=',' . join(tids[person_name]),
                     uid='%s@%s' % (person_name, NAMESPACE),
                     label=LABELS[person_name])
    pprint(response)

    print("Training set for %s" % person_name)
    response = client.faces_train('%s@%s' % (person_name, NAMESPACE))
    pprint(response)

# Testing step
for person_name in ['andrei', 'diana']:
    face_samples = []

    for image in listdir(TEST_FOLDER.format(person_name=person_name)):
        image_url = "%s%s" % (PREFIX_URL.format(person_name=person_name), image)
        response = requests.get(image_url)
        if response.status_code == 200:
            face_samples.append(image_url)
    face_samples = ','.join(face_samples)

    print("Recognizing %s..." % person_name)
    response = client.faces_recognize('all', face_samples, namespace=NAMESPACE)
    pprint(response)

    print("Results for %s sample:" % person_name)
    pprint(response['photos'][0]['tags'][0]['uids'])


""" Output:

=============================== SHORT VERSION ===============================

Results for andrei sample:

[{u'confidence': 42, u'uid': u'andrei@amilab-test2'},
 {u'confidence': 37, u'uid': u'diana@amilab-test2'}]

Results for diana sample:

[{u'confidence': 74, u'uid': u'diana@amilab-test2'},
 {u'confidence': 30, u'uid': u'andrei@amilab-test2'}]


=============================== LONG VERSION ===============================

Detecting faces for andrei...

{u'operation_id': u'69d26bff99cc433892bae8900b321dbc',
 u'photos': [{u'height': 268,
              u'pid': u'F@00fd467a1bbfe7cb5835766739cd8de5_d7699a6252775',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 59,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 72,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 43,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 65,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 65,
                                                      u'value': u'false'}},
                         u'center': {u'x': 49.25, u'y': 50.37},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.21, u'y': 42.54},
                         u'eye_right': {u'x': 39.93, u'y': 44.03},
                         u'height': 33.21,
                         u'manual': False,
                         u'mouth_center': {u'x': 52.99, u'y': 63.06},
                         u'nose': {u'x': 49.63, u'y': 51.12},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -7,
                         u'tid': u'TEMP_F@00fd467a1bbfe7cb5835766700840087_d7699a6252775_49.25_50.37_0_1',
                         u'uids': [],
                         u'width': 33.21,
                         u'yaw': 1}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/50156d53-39be-4386-9ed3-b45abb1bbb90.jpg',
              u'width': 268},
             {u'height': 328,
              u'pid': u'F@0f43fa6a531960077ca53f2551ec1732_3b525f9709a49',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 47,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 73,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 72,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 76,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 49,
                                                      u'value': u'false'}},
                         u'center': {u'x': 47.87, u'y': 52.44},
                         u'confirmed': False,
                         u'eye_left': {u'x': 57.93, u'y': 43.29},
                         u'eye_right': {u'x': 39.63, u'y': 47.56},
                         u'height': 34.45,
                         u'manual': False,
                         u'mouth_center': {u'x': 54.88, u'y': 63.72},
                         u'nose': {u'x': 52.74, u'y': 52.74},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -15,
                         u'tid': u'TEMP_F@0f43fa6a531960077ca53f25009d00ac_3b525f9709a49_47.87_52.44_0_1',
                         u'uids': [],
                         u'width': 34.45,
                         u'yaw': -12}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/66da04b5-b9f8-4a76-a622-338b7ed15432.jpg',
              u'width': 328},
             {u'height': 248,
              u'pid': u'F@0185102855ccd6933371560157c4ffd0_9c74a27bc85c4',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 31,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 71,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 80,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 56,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 82,
                                                      u'value': u'false'}},
                         u'center': {u'x': 48.79, u'y': 51.21},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.06, u'y': 41.94},
                         u'eye_right': {u'x': 39.52, u'y': 46.37},
                         u'height': 34.27,
                         u'manual': False,
                         u'mouth_center': {u'x': 50.81, u'y': 62.9},
                         u'nose': {u'x': 51.21, u'y': 52.82},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -13,
                         u'tid': u'TEMP_F@0185102855ccd693337156010079007f_9c74a27bc85c4_48.79_51.21_0_1',
                         u'uids': [],
                         u'width': 34.27,
                         u'yaw': -5}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/68fce73f-8052-44f6-a55f-3639c9e6dd04.jpg',
              u'width': 248},
             {u'height': 360,
              u'pid': u'F@0a1f7490674c32282d5226402a3ddbba_0a51794a27c19',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 32,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 76,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 87,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 25,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 57,
                                                      u'value': u'false'}},
                         u'center': {u'x': 48.89, u'y': 52.22},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.89, u'y': 43.89},
                         u'eye_right': {u'x': 41.39, u'y': 45.28},
                         u'height': 34.72,
                         u'manual': False,
                         u'mouth_center': {u'x': 52.22, u'y': 63.61},
                         u'nose': {u'x': 51.94, u'y': 52.5},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -4,
                         u'tid': u'TEMP_F@0a1f7490674c32282d52264000b000bc_0a51794a27c19_48.89_52.22_0_1',
                         u'uids': [],
                         u'width': 34.72,
                         u'yaw': -6}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/6bbeb540-a2bb-4956-8281-2d4d5f3c4a90.jpg',
              u'width': 360},
             {u'height': 328,
              u'pid': u'F@093901107fb6215a53ae2dbd65bb992e_0974ee9d0fe73',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 48,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 78,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 63,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 38,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 61,
                                                      u'value': u'false'}},
                         u'center': {u'x': 48.17, u'y': 51.83},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.84, u'y': 45.43},
                         u'eye_right': {u'x': 41.46, u'y': 43.29},
                         u'height': 33.54,
                         u'manual': False,
                         u'mouth_center': {u'x': 49.39, u'y': 63.11},
                         u'nose': {u'x': 50.3, u'y': 53.66},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': 4,
                         u'tid': u'TEMP_F@093901107fb6215a53ae2dbd009e00aa_0974ee9d0fe73_48.17_51.83_0_1',
                         u'uids': [],
                         u'width': 33.54,
                         u'yaw': -6}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/3e632e6f-c222-4784-8ce9-7eb1594c37b2.jpg',
              u'width': 328},
             {u'height': 256,
              u'pid': u'F@0c3065786ad46ae821de9852644ed0de_0ff19a0e2e7a1',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 39,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 73,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 74,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 66,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 83,
                                                      u'value': u'false'}},
                         u'center': {u'x': 51.17, u'y': 51.56},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.2, u'y': 42.19},
                         u'eye_right': {u'x': 40.62, u'y': 48.05},
                         u'height': 32.81,
                         u'manual': False,
                         u'mouth_center': {u'x': 55.08, u'y': 63.28},
                         u'nose': {u'x': 51.95, u'y': 53.12},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -20,
                         u'tid': u'TEMP_F@0c3065786ad46ae821de985200830084_0ff19a0e2e7a1_51.17_51.56_0_1',
                         u'uids': [],
                         u'width': 32.81,
                         u'yaw': 0}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/60cc071b-e6b3-4235-9c4e-5e4e5a8d7c02.jpg',
              u'width': 256},
             {u'height': 220,
              u'pid': u'F@00a678ba1b3671e151aa8caa159b7744_cc7b6b23c8837',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 36,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 79,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 40,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 100,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 72,
                                                      u'value': u'false'}},
                         u'center': {u'x': 50.0, u'y': 50.45},
                         u'confirmed': False,
                         u'eye_left': {u'x': 57.73, u'y': 44.55},
                         u'eye_right': {u'x': 41.36, u'y': 45.0},
                         u'height': 31.36,
                         u'manual': False,
                         u'mouth_center': {u'x': 50.45, u'y': 61.36},
                         u'nose': {u'x': 50.45, u'y': 51.82},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -2,
                         u'tid': u'TEMP_F@00a678ba1b3671e151aa8caa006e006f_cc7b6b23c8837_50.00_50.45_0_1',
                         u'uids': [],
                         u'width': 31.36,
                         u'yaw': 3}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/556b867d-2079-4cbe-b54b-8646537fbc0f.jpg',
              u'width': 220}],
 u'status': u'success',
 u'usage': {u'limit': 100,
            u'remaining': 100,
            u'reset_time': 1373629450,
            u'reset_time_text': u'Fri, 12 July 2013 11:44:10 +0000',
            u'used': 7}}

Saving tags for andrei...

{u'operation_id': u'69d26bff99cc433892bae8900b321dbc',
 u'photos': [{u'height': 268,
              u'pid': u'F@00fd467a1bbfe7cb5835766739cd8de5_d7699a6252775',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 59,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 72,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 43,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 65,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 65,
                                                      u'value': u'false'}},
                         u'center': {u'x': 49.25, u'y': 50.37},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.21, u'y': 42.54},
                         u'eye_right': {u'x': 39.93, u'y': 44.03},
                         u'height': 33.21,
                         u'manual': False,
                         u'mouth_center': {u'x': 52.99, u'y': 63.06},
                         u'nose': {u'x': 49.63, u'y': 51.12},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -7,
                         u'tid': u'TEMP_F@00fd467a1bbfe7cb5835766700840087_d7699a6252775_49.25_50.37_0_1',
                         u'uids': [],
                         u'width': 33.21,
                         u'yaw': 1}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/50156d53-39be-4386-9ed3-b45abb1bbb90.jpg',
              u'width': 268},
             {u'height': 328,
              u'pid': u'F@0f43fa6a531960077ca53f2551ec1732_3b525f9709a49',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 47,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 73,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 72,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 76,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 49,
                                                      u'value': u'false'}},
                         u'center': {u'x': 47.87, u'y': 52.44},
                         u'confirmed': False,
                         u'eye_left': {u'x': 57.93, u'y': 43.29},
                         u'eye_right': {u'x': 39.63, u'y': 47.56},
                         u'height': 34.45,
                         u'manual': False,
                         u'mouth_center': {u'x': 54.88, u'y': 63.72},
                         u'nose': {u'x': 52.74, u'y': 52.74},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -15,
                         u'tid': u'TEMP_F@0f43fa6a531960077ca53f25009d00ac_3b525f9709a49_47.87_52.44_0_1',
                         u'uids': [],
                         u'width': 34.45,
                         u'yaw': -12}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/66da04b5-b9f8-4a76-a622-338b7ed15432.jpg',
              u'width': 328},
             {u'height': 248,
              u'pid': u'F@0185102855ccd6933371560157c4ffd0_9c74a27bc85c4',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 31,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 71,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 80,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 56,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 82,
                                                      u'value': u'false'}},
                         u'center': {u'x': 48.79, u'y': 51.21},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.06, u'y': 41.94},
                         u'eye_right': {u'x': 39.52, u'y': 46.37},
                         u'height': 34.27,
                         u'manual': False,
                         u'mouth_center': {u'x': 50.81, u'y': 62.9},
                         u'nose': {u'x': 51.21, u'y': 52.82},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -13,
                         u'tid': u'TEMP_F@0185102855ccd693337156010079007f_9c74a27bc85c4_48.79_51.21_0_1',
                         u'uids': [],
                         u'width': 34.27,
                         u'yaw': -5}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/68fce73f-8052-44f6-a55f-3639c9e6dd04.jpg',
              u'width': 248},
             {u'height': 360,
              u'pid': u'F@0a1f7490674c32282d5226402a3ddbba_0a51794a27c19',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 32,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 76,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 87,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 25,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 57,
                                                      u'value': u'false'}},
                         u'center': {u'x': 48.89, u'y': 52.22},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.89, u'y': 43.89},
                         u'eye_right': {u'x': 41.39, u'y': 45.28},
                         u'height': 34.72,
                         u'manual': False,
                         u'mouth_center': {u'x': 52.22, u'y': 63.61},
                         u'nose': {u'x': 51.94, u'y': 52.5},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -4,
                         u'tid': u'TEMP_F@0a1f7490674c32282d52264000b000bc_0a51794a27c19_48.89_52.22_0_1',
                         u'uids': [],
                         u'width': 34.72,
                         u'yaw': -6}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/6bbeb540-a2bb-4956-8281-2d4d5f3c4a90.jpg',
              u'width': 360},
             {u'height': 328,
              u'pid': u'F@093901107fb6215a53ae2dbd65bb992e_0974ee9d0fe73',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 48,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 78,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 63,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 38,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 61,
                                                      u'value': u'false'}},
                         u'center': {u'x': 48.17, u'y': 51.83},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.84, u'y': 45.43},
                         u'eye_right': {u'x': 41.46, u'y': 43.29},
                         u'height': 33.54,
                         u'manual': False,
                         u'mouth_center': {u'x': 49.39, u'y': 63.11},
                         u'nose': {u'x': 50.3, u'y': 53.66},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': 4,
                         u'tid': u'TEMP_F@093901107fb6215a53ae2dbd009e00aa_0974ee9d0fe73_48.17_51.83_0_1',
                         u'uids': [],
                         u'width': 33.54,
                         u'yaw': -6}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/3e632e6f-c222-4784-8ce9-7eb1594c37b2.jpg',
              u'width': 328},
             {u'height': 256,
              u'pid': u'F@0c3065786ad46ae821de9852644ed0de_0ff19a0e2e7a1',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 39,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 73,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 74,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 66,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 83,
                                                      u'value': u'false'}},
                         u'center': {u'x': 51.17, u'y': 51.56},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.2, u'y': 42.19},
                         u'eye_right': {u'x': 40.62, u'y': 48.05},
                         u'height': 32.81,
                         u'manual': False,
                         u'mouth_center': {u'x': 55.08, u'y': 63.28},
                         u'nose': {u'x': 51.95, u'y': 53.12},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -20,
                         u'tid': u'TEMP_F@0c3065786ad46ae821de985200830084_0ff19a0e2e7a1_51.17_51.56_0_1',
                         u'uids': [],
                         u'width': 32.81,
                         u'yaw': 0}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/60cc071b-e6b3-4235-9c4e-5e4e5a8d7c02.jpg',
              u'width': 256},
             {u'height': 220,
              u'pid': u'F@00a678ba1b3671e151aa8caa159b7744_cc7b6b23c8837',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 36,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 79,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 40,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 100,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 72,
                                                      u'value': u'false'}},
                         u'center': {u'x': 50.0, u'y': 50.45},
                         u'confirmed': False,
                         u'eye_left': {u'x': 57.73, u'y': 44.55},
                         u'eye_right': {u'x': 41.36, u'y': 45.0},
                         u'height': 31.36,
                         u'manual': False,
                         u'mouth_center': {u'x': 50.45, u'y': 61.36},
                         u'nose': {u'x': 50.45, u'y': 51.82},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -2,
                         u'tid': u'TEMP_F@00a678ba1b3671e151aa8caa006e006f_cc7b6b23c8837_50.00_50.45_0_1',
                         u'uids': [],
                         u'width': 31.36,
                         u'yaw': 3}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/556b867d-2079-4cbe-b54b-8646537fbc0f.jpg',
              u'width': 220}],
 u'status': u'success',
 u'usage': {u'limit': 100,
            u'remaining': 100,
            u'reset_time': 1373629450,
            u'reset_time_text': u'Fri, 12 July 2013 11:44:10 +0000',
            u'used': 7}}

Training set for andrei...

{u'created': [{u'last_trained': 1373628718,
               u'training_in_progress': False,
               u'training_set_size': 7,
               u'uid': u'andrei@amilab-test2'}],
 u'operation_id': u'88b4e59f7870486a9199a673547b69c3',
 u'status': u'success'}

Detecting faces for diana...

{u'operation_id': u'e3dacd2ff0964dad832b53c96ca33b67',
 u'photos': [{u'height': 228,
              u'pid': u'F@0f25bc17320061de10687b7418ea9d81_4fc6c8ac2dec9',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 31,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 76,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 4,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 67,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 100,
                                                      u'value': u'false'}},
                         u'center': {u'x': 51.75, u'y': 52.63},
                         u'confirmed': False,
                         u'eye_left': {u'x': 57.02, u'y': 44.3},
                         u'eye_right': {u'x': 40.35, u'y': 46.49},
                         u'height': 32.46,
                         u'manual': False,
                         u'mouth_center': {u'x': 52.19, u'y': 63.16},
                         u'nose': {u'x': 48.68, u'y': 54.39},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -5,
                         u'tid': u'TEMP_F@0f25bc17320061de10687b7400760078_4fc6c8ac2dec9_51.75_52.63_0_1',
                         u'uids': [],
                         u'width': 32.46,
                         u'yaw': 10}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/0ee95112-5715-437f-8a17-0680cdc56a8e.jpg',
              u'width': 228},
             {u'height': 244,
              u'pid': u'F@0ec329b02345cd5c107fb5ae443c5757_129712f95cb20',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 32,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 75,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 36,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 100,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 66,
                                                      u'value': u'false'}},
                         u'center': {u'x': 53.69, u'y': 50.41},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.2, u'y': 42.21},
                         u'eye_right': {u'x': 40.57, u'y': 45.49},
                         u'height': 33.2,
                         u'manual': False,
                         u'mouth_center': {u'x': 54.51, u'y': 61.07},
                         u'nose': {u'x': 50.41, u'y': 54.92},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -7,
                         u'tid': u'TEMP_F@0ec329b02345cd5c107fb5ae0083007b_129712f95cb20_53.69_50.41_0_1',
                         u'uids': [],
                         u'width': 33.2,
                         u'yaw': 17}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/58b880d7-be6d-4842-b2e6-a9a970a9e577.jpg',
              u'width': 244},
             {u'height': 256,
              u'pid': u'F@0c0e3b9a19038f63355e2b035eb4c3b4_9fb5335a22c3d',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 32,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 80,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 2,
                                                     u'value': u'female'},
                                         u'glasses': {u'confidence': 100,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 100,
                                                      u'value': u'false'}},
                         u'center': {u'x': 50.78, u'y': 51.95},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.59, u'y': 43.36},
                         u'eye_right': {u'x': 41.02, u'y': 45.31},
                         u'height': 33.98,
                         u'label': u'Diana Tatu',
                         u'manual': False,
                         u'mouth_center': {u'x': 52.34, u'y': 63.28},
                         u'nose': {u'x': 50.78, u'y': 54.3},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -5,
                         u'tid': u'TEMP_F@0c0e3b9a19038f63355e2b0300820085_9fb5335a22c3d_50.78_51.95_0_1',
                         u'uids': [],
                         u'width': 33.98,
                         u'yaw': 3}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/08062843-c432-435c-8b83-62079d682667.jpg',
              u'width': 256},
             {u'height': 216,
              u'pid': u'F@06d5cba841dc134618a0439c40624664_5c4fa87016d50',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 9,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 70,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 26,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 46,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 84,
                                                      u'value': u'false'}},
                         u'center': {u'x': 48.61, u'y': 52.78},
                         u'confirmed': False,
                         u'eye_left': {u'x': 59.26, u'y': 43.98},
                         u'eye_right': {u'x': 42.13, u'y': 45.37},
                         u'height': 34.26,
                         u'manual': False,
                         u'mouth_center': {u'x': 54.17, u'y': 62.96},
                         u'nose': {u'x': 52.31, u'y': 55.09},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -3,
                         u'tid': u'TEMP_F@06d5cba841dc134618a0439c00690072_5c4fa87016d50_48.61_52.78_0_1',
                         u'uids': [],
                         u'width': 34.26,
                         u'yaw': -18}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/66585049-be7c-495a-b172-25193ad3d862.jpg',
              u'width': 216},
             {u'height': 220,
              u'pid': u'F@0fa70fb236982fc41809a1a43ce04657_863d786e3b739',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 27,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 65,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 2,
                                                     u'value': u'female'},
                                         u'glasses': {u'confidence': 57,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 100,
                                                      u'value': u'false'}},
                         u'center': {u'x': 50.0, u'y': 51.36},
                         u'confirmed': False,
                         u'eye_left': {u'x': 57.73, u'y': 41.82},
                         u'eye_right': {u'x': 40.0, u'y': 44.55},
                         u'height': 32.73,
                         u'manual': False,
                         u'mouth_center': {u'x': 49.55, u'y': 63.18},
                         u'nose': {u'x': 51.36, u'y': 54.09},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -9,
                         u'tid': u'TEMP_F@0fa70fb236982fc41809a1a4006e0071_863d786e3b739_50.00_51.36_0_1',
                         u'uids': [],
                         u'width': 32.73,
                         u'yaw': -2}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/8d44900f-4db1-493c-b012-a2e5cb1aa4a0.jpg',
              u'width': 220},
             {u'height': 212,
              u'pid': u'F@056a9eeb53c998661b79aecf0fea1c38_ffd9c947a162c',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 25,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 72,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 14,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 50,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 78,
                                                      u'value': u'false'}},
                         u'center': {u'x': 48.58, u'y': 52.83},
                         u'confirmed': False,
                         u'eye_left': {u'x': 57.08, u'y': 44.81},
                         u'eye_right': {u'x': 40.09, u'y': 45.28},
                         u'height': 33.96,
                         u'manual': False,
                         u'mouth_center': {u'x': 44.34, u'y': 62.26},
                         u'nose': {u'x': 49.06, u'y': 55.66},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': 1,
                         u'tid': u'TEMP_F@056a9eeb53c998661b79aecf00670070_ffd9c947a162c_48.58_52.83_0_1',
                         u'uids': [],
                         u'width': 33.96,
                         u'yaw': 0}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/95210928-02c2-4d40-aea4-418979a0ceb6.jpg',
              u'width': 212},
             {u'height': 244,
              u'pid': u'F@0fcbeafe4b902e36095a12143b6c028a_e6fa52ff076ad',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 20,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 66,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 25,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 83,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 85,
                                                      u'value': u'false'}},
                         u'center': {u'x': 54.92, u'y': 50.82},
                         u'confirmed': False,
                         u'eye_left': {u'x': 59.02, u'y': 41.39},
                         u'eye_right': {u'x': 40.98, u'y': 46.72},
                         u'height': 34.02,
                         u'manual': False,
                         u'mouth_center': {u'x': 59.02, u'y': 63.11},
                         u'nose': {u'x': 51.64, u'y': 55.74},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -14,
                         u'tid': u'TEMP_F@0fcbeafe4b902e36095a12140086007c_e6fa52ff076ad_54.92_50.82_0_1',
                         u'uids': [],
                         u'width': 34.02,
                         u'yaw': 19}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/a19369f1-782d-4155-bc20-a71ac34ad186.jpg',
              u'width': 244},
             {u'height': 212,
              u'pid': u'F@0a05afe30b00a9a708e82b027316be7b_13e5a1a1822d4',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 16,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 64,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 16,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 25,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 82,
                                                      u'value': u'false'}},
                         u'center': {u'x': 46.23, u'y': 51.89},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.96, u'y': 44.81},
                         u'eye_right': {u'x': 41.51, u'y': 43.87},
                         u'height': 34.43,
                         u'manual': False,
                         u'mouth_center': {u'x': 45.28, u'y': 63.68},
                         u'nose': {u'x': 50.47, u'y': 55.19},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': 4,
                         u'tid': u'TEMP_F@0a05afe30b00a9a708e82b020062006e_13e5a1a1822d4_46.23_51.89_0_1',
                         u'uids': [],
                         u'width': 34.43,
                         u'yaw': -18}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/5fe5b39a-b710-4c47-85e5-a05055b31c55.jpg',
              u'width': 212},
             {u'height': 208,
              u'pid': u'F@09c7f874273a87531b71455f1519d648_b39193c6fba60',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 35,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 71,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 0,
                                                     u'value': u'female'},
                                         u'glasses': {u'confidence': 80,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 58,
                                                      u'value': u'false'}},
                         u'center': {u'x': 50.96, u'y': 51.92},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.65, u'y': 43.27},
                         u'eye_right': {u'x': 40.87, u'y': 46.15},
                         u'height': 35.1,
                         u'manual': False,
                         u'mouth_center': {u'x': 47.6, u'y': 63.46},
                         u'nose': {u'x': 51.92, u'y': 55.77},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -8,
                         u'tid': u'TEMP_F@09c7f874273a87531b71455f006a006c_b39193c6fba60_50.96_51.92_0_1',
                         u'uids': [],
                         u'width': 35.1,
                         u'yaw': 0}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/4161f127-81f0-4ac4-a39d-bc243d2f9dd2.jpg',
              u'width': 208}],
 u'status': u'success',
 u'usage': {u'limit': 100,
            u'remaining': 93,
            u'reset_time': 1373629450,
            u'reset_time_text': u'Fri, 12 July 2013 11:44:10 +0000',
            u'used': 16}}

Saving tags for diana...

{u'operation_id': u'e3dacd2ff0964dad832b53c96ca33b67',
 u'photos': [{u'height': 228,
              u'pid': u'F@0f25bc17320061de10687b7418ea9d81_4fc6c8ac2dec9',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 31,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 76,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 4,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 67,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 100,
                                                      u'value': u'false'}},
                         u'center': {u'x': 51.75, u'y': 52.63},
                         u'confirmed': False,
                         u'eye_left': {u'x': 57.02, u'y': 44.3},
                         u'eye_right': {u'x': 40.35, u'y': 46.49},
                         u'height': 32.46,
                         u'manual': False,
                         u'mouth_center': {u'x': 52.19, u'y': 63.16},
                         u'nose': {u'x': 48.68, u'y': 54.39},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -5,
                         u'tid': u'TEMP_F@0f25bc17320061de10687b7400760078_4fc6c8ac2dec9_51.75_52.63_0_1',
                         u'uids': [],
                         u'width': 32.46,
                         u'yaw': 10}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/0ee95112-5715-437f-8a17-0680cdc56a8e.jpg',
              u'width': 228},
             {u'height': 244,
              u'pid': u'F@0ec329b02345cd5c107fb5ae443c5757_129712f95cb20',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 32,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 75,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 36,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 100,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 66,
                                                      u'value': u'false'}},
                         u'center': {u'x': 53.69, u'y': 50.41},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.2, u'y': 42.21},
                         u'eye_right': {u'x': 40.57, u'y': 45.49},
                         u'height': 33.2,
                         u'manual': False,
                         u'mouth_center': {u'x': 54.51, u'y': 61.07},
                         u'nose': {u'x': 50.41, u'y': 54.92},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -7,
                         u'tid': u'TEMP_F@0ec329b02345cd5c107fb5ae0083007b_129712f95cb20_53.69_50.41_0_1',
                         u'uids': [],
                         u'width': 33.2,
                         u'yaw': 17}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/58b880d7-be6d-4842-b2e6-a9a970a9e577.jpg',
              u'width': 244},
             {u'height': 256,
              u'pid': u'F@0c0e3b9a19038f63355e2b035eb4c3b4_9fb5335a22c3d',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 32,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 80,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 2,
                                                     u'value': u'female'},
                                         u'glasses': {u'confidence': 100,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 100,
                                                      u'value': u'false'}},
                         u'center': {u'x': 50.78, u'y': 51.95},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.59, u'y': 43.36},
                         u'eye_right': {u'x': 41.02, u'y': 45.31},
                         u'height': 33.98,
                         u'label': u'Diana Tatu',
                         u'manual': False,
                         u'mouth_center': {u'x': 52.34, u'y': 63.28},
                         u'nose': {u'x': 50.78, u'y': 54.3},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -5,
                         u'tid': u'TEMP_F@0c0e3b9a19038f63355e2b0300820085_9fb5335a22c3d_50.78_51.95_0_1',
                         u'uids': [],
                         u'width': 33.98,
                         u'yaw': 3}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/08062843-c432-435c-8b83-62079d682667.jpg',
              u'width': 256},
             {u'height': 216,
              u'pid': u'F@06d5cba841dc134618a0439c40624664_5c4fa87016d50',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 9,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 70,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 26,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 46,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 84,
                                                      u'value': u'false'}},
                         u'center': {u'x': 48.61, u'y': 52.78},
                         u'confirmed': False,
                         u'eye_left': {u'x': 59.26, u'y': 43.98},
                         u'eye_right': {u'x': 42.13, u'y': 45.37},
                         u'height': 34.26,
                         u'manual': False,
                         u'mouth_center': {u'x': 54.17, u'y': 62.96},
                         u'nose': {u'x': 52.31, u'y': 55.09},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -3,
                         u'tid': u'TEMP_F@06d5cba841dc134618a0439c00690072_5c4fa87016d50_48.61_52.78_0_1',
                         u'uids': [],
                         u'width': 34.26,
                         u'yaw': -18}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/66585049-be7c-495a-b172-25193ad3d862.jpg',
              u'width': 216},
             {u'height': 220,
              u'pid': u'F@0fa70fb236982fc41809a1a43ce04657_863d786e3b739',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 27,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 65,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 2,
                                                     u'value': u'female'},
                                         u'glasses': {u'confidence': 57,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 100,
                                                      u'value': u'false'}},
                         u'center': {u'x': 50.0, u'y': 51.36},
                         u'confirmed': False,
                         u'eye_left': {u'x': 57.73, u'y': 41.82},
                         u'eye_right': {u'x': 40.0, u'y': 44.55},
                         u'height': 32.73,
                         u'manual': False,
                         u'mouth_center': {u'x': 49.55, u'y': 63.18},
                         u'nose': {u'x': 51.36, u'y': 54.09},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -9,
                         u'tid': u'TEMP_F@0fa70fb236982fc41809a1a4006e0071_863d786e3b739_50.00_51.36_0_1',
                         u'uids': [],
                         u'width': 32.73,
                         u'yaw': -2}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/8d44900f-4db1-493c-b012-a2e5cb1aa4a0.jpg',
              u'width': 220},
             {u'height': 212,
              u'pid': u'F@056a9eeb53c998661b79aecf0fea1c38_ffd9c947a162c',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 25,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 72,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 14,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 50,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 78,
                                                      u'value': u'false'}},
                         u'center': {u'x': 48.58, u'y': 52.83},
                         u'confirmed': False,
                         u'eye_left': {u'x': 57.08, u'y': 44.81},
                         u'eye_right': {u'x': 40.09, u'y': 45.28},
                         u'height': 33.96,
                         u'manual': False,
                         u'mouth_center': {u'x': 44.34, u'y': 62.26},
                         u'nose': {u'x': 49.06, u'y': 55.66},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': 1,
                         u'tid': u'TEMP_F@056a9eeb53c998661b79aecf00670070_ffd9c947a162c_48.58_52.83_0_1',
                         u'uids': [],
                         u'width': 33.96,
                         u'yaw': 0}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/95210928-02c2-4d40-aea4-418979a0ceb6.jpg',
              u'width': 212},
             {u'height': 244,
              u'pid': u'F@0fcbeafe4b902e36095a12143b6c028a_e6fa52ff076ad',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 20,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 66,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 25,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 83,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 85,
                                                      u'value': u'false'}},
                         u'center': {u'x': 54.92, u'y': 50.82},
                         u'confirmed': False,
                         u'eye_left': {u'x': 59.02, u'y': 41.39},
                         u'eye_right': {u'x': 40.98, u'y': 46.72},
                         u'height': 34.02,
                         u'manual': False,
                         u'mouth_center': {u'x': 59.02, u'y': 63.11},
                         u'nose': {u'x': 51.64, u'y': 55.74},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -14,
                         u'tid': u'TEMP_F@0fcbeafe4b902e36095a12140086007c_e6fa52ff076ad_54.92_50.82_0_1',
                         u'uids': [],
                         u'width': 34.02,
                         u'yaw': 19}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/a19369f1-782d-4155-bc20-a71ac34ad186.jpg',
              u'width': 244},
             {u'height': 212,
              u'pid': u'F@0a05afe30b00a9a708e82b027316be7b_13e5a1a1822d4',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 16,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 64,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 16,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 25,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 82,
                                                      u'value': u'false'}},
                         u'center': {u'x': 46.23, u'y': 51.89},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.96, u'y': 44.81},
                         u'eye_right': {u'x': 41.51, u'y': 43.87},
                         u'height': 34.43,
                         u'manual': False,
                         u'mouth_center': {u'x': 45.28, u'y': 63.68},
                         u'nose': {u'x': 50.47, u'y': 55.19},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': 4,
                         u'tid': u'TEMP_F@0a05afe30b00a9a708e82b020062006e_13e5a1a1822d4_46.23_51.89_0_1',
                         u'uids': [],
                         u'width': 34.43,
                         u'yaw': -18}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/5fe5b39a-b710-4c47-85e5-a05055b31c55.jpg',
              u'width': 212},
             {u'height': 208,
              u'pid': u'F@09c7f874273a87531b71455f1519d648_b39193c6fba60',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 35,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 71,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 0,
                                                     u'value': u'female'},
                                         u'glasses': {u'confidence': 80,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 58,
                                                      u'value': u'false'}},
                         u'center': {u'x': 50.96, u'y': 51.92},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.65, u'y': 43.27},
                         u'eye_right': {u'x': 40.87, u'y': 46.15},
                         u'height': 35.1,
                         u'manual': False,
                         u'mouth_center': {u'x': 47.6, u'y': 63.46},
                         u'nose': {u'x': 51.92, u'y': 55.77},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': -8,
                         u'tid': u'TEMP_F@09c7f874273a87531b71455f006a006c_b39193c6fba60_50.96_51.92_0_1',
                         u'uids': [],
                         u'width': 35.1,
                         u'yaw': 0}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/4161f127-81f0-4ac4-a39d-bc243d2f9dd2.jpg',
              u'width': 208}],
 u'status': u'success',
 u'usage': {u'limit': 100,
            u'remaining': 93,
            u'reset_time': 1373629450,
            u'reset_time_text': u'Fri, 12 July 2013 11:44:10 +0000',
            u'used': 16}}

Training set for diana...

{u'created': [{u'last_trained': 1373628884,
               u'training_in_progress': False,
               u'training_set_size': 9,
               u'uid': u'diana@amilab-test2'}],
 u'operation_id': u'29ce0425e344443b8b950a8144b2b9f3',
 u'status': u'success'}

Recognizing andrei...

{u'operation_id': u'66be55c590e84eaba66df1caedbddc5f',
 u'photos': [{u'height': 224,
              u'pid': u'F@003ca177771006581fed375448920467_914dcd9bb0b42',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 54,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 70,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 11,
                                                     u'value': u'male'},
                                         u'glasses': {u'confidence': 68,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 47,
                                                      u'value': u'false'}},
                         u'center': {u'x': 54.02, u'y': 52.68},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.93, u'y': 45.54},
                         u'eye_right': {u'x': 42.41, u'y': 42.86},
                         u'height': 32.59,
                         u'manual': False,
                         u'mouth_center': {u'x': 43.75, u'y': 63.39},
                         u'nose': {u'x': 45.98, u'y': 55.36},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': 7,
                         u'threshold': 59,
                         u'tid': u'TEMP_F@003ca177771006581fed375400790076_914dcd9bb0b42_54.02_52.68_0_1',
                         u'uids': [{u'confidence': 42,
                                    u'uid': u'andrei@amilab-test2'},
                                   {u'confidence': 37,
                                    u'uid': u'diana@amilab-test2'}],
                         u'width': 32.59,
                         u'yaw': 31}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/andrei@amilab.ro/d455a677-e122-46b1-96c3-0b4cc5e8d657.jpg',
              u'width': 224}],
 u'status': u'success',
 u'usage': {u'limit': 100,
            u'remaining': 84,
            u'reset_time': 1373629450,
            u'reset_time_text': u'Fri, 12 July 2013 11:44:10 +0000',
            u'used': 17}}

Results for andrei sample:

[{u'confidence': 42, u'uid': u'andrei@amilab-test2'},
 {u'confidence': 37, u'uid': u'diana@amilab-test2'}]

Recognizing diana...

{u'operation_id': u'f2765f4f90ea42cb863eadd1af2d2f7e',
 u'photos': [{u'height': 248,
              u'pid': u'F@02ed2a3a3f55e0e705dd8cd41c8457f2_237fd01866a8d',
              u'tags': [{u'attributes': {u'dark_glasses': {u'confidence': 15,
                                                           u'value': u'false'},
                                         u'face': {u'confidence': 66,
                                                   u'value': u'true'},
                                         u'gender': {u'confidence': 2,
                                                     u'value': u'female'},
                                         u'glasses': {u'confidence': 41,
                                                      u'value': u'false'},
                                         u'smiling': {u'confidence': 100,
                                                      u'value': u'false'}},
                         u'center': {u'x': 49.19, u'y': 53.63},
                         u'confirmed': False,
                         u'eye_left': {u'x': 58.87, u'y': 44.76},
                         u'eye_right': {u'x': 40.32, u'y': 45.16},
                         u'height': 37.5,
                         u'manual': False,
                         u'mouth_center': {u'x': 49.6, u'y': 64.92},
                         u'nose': {u'x': 49.6, u'y': 56.45},
                         u'pitch': 0,
                         u'recognizable': True,
                         u'roll': 1,
                         u'threshold': 59,
                         u'tid': u'TEMP_F@02ed2a3a3f55e0e705dd8cd4007a0085_237fd01866a8d_49.19_53.63_0_1',
                         u'uids': [{u'confidence': 74,
                                    u'uid': u'diana@amilab-test2'},
                                   {u'confidence': 30,
                                    u'uid': u'andrei@amilab-test2'}],
                         u'width': 37.5,
                         u'yaw': 0}],
              u'url': u'https://raw.github.com/ami-lab/AmI-Platform/f6f36c26c2ce29ddec8b714f9650bf9ea7e40149/face_samples/diana@amilab.ro/7f1a13e0-4c16-4dd6-a2cf-09b06f7c0874.jpg',
              u'width': 248}],
 u'status': u'success',
 u'usage': {u'limit': 100,
            u'remaining': 83,
            u'reset_time': 1373629450,
            u'reset_time_text': u'Fri, 12 July 2013 11:44:10 +0000',
            u'used': 18}}

Results for diana sample:

[{u'confidence': 74, u'uid': u'diana@amilab-test2'},
 {u'confidence': 30, u'uid': u'andrei@amilab-test2'}]
